### PR TITLE
Dutch draft for the GSoC2019Flyer

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by ftyers** [comment]
@Begasus thanks for your PR, could you rename the file to use 639-3 language codes? e.g. Dutch is `nld`.

**Comment by Begasus** [comment]
Hi @flyers this could be used for nl_NL and nl_BE so how should I rename the files extentions to the correct format?

**Comment by Begasus** [comment]
Hope this covers it :)

**Comment by ftyers** [comment]
Looks good, thanks @Begasus !

**Pull request merged**
